// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTranslator.Api.Data;

#nullable disable

namespace MyTranslator.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MyTranslator.Api.Data.ApiToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("ApiTokens", (string)null);
                });

            modelBuilder.Entity("MyTranslator.Api.Data.ProtectedBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChapterJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceUnitOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "SourceUnitOrder")
                        .IsUnique();

                    b.ToTable("ProtectedBlocks", (string)null);
                });

            modelBuilder.Entity("MyTranslator.Api.Data.TranslationSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChapterJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfirmationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarkupTableJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceUnitOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetText")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateToken")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "Order")
                        .IsUnique();

                    b.ToTable("TranslationSegments", (string)null);
                });

            modelBuilder.Entity("MyTranslator.Api.Data.TranslationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveTaskId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtractionRevision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedSegments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("FailureRetryable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessedSegments")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedSegments")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkippedExistingSegments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SucceededSegments")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSegments")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActiveTaskId")
                        .IsUnique()
                        .HasFilter("\"ActiveTaskId\" IS NOT NULL");

                    b.HasIndex("TaskId", "CreatedAt");

                    b.ToTable("TranslationRuns", (string)null);
                });

            modelBuilder.Entity("MyTranslator.Api.Data.TranslationRunFailure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Retryable")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SegmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SegmentOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "SegmentOrder")
                        .IsUnique();

                    b.ToTable("TranslationRunFailures", (string)null);
                });

            modelBuilder.Entity("MyTranslator.Api.Data.TranslationTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtractionRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalEncoding")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProtectedBlockCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReconstructionTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SegmentationEffective")
                        .HasColumnType("TEXT");

                    b.Property<string>("SegmentationReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("SegmentationRecommended")
                        .HasColumnType("TEXT");

                    b.Property<string>("SegmentationRequested")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SourceBytes")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TranslationTasks", (string)null);
                });

            modelBuilder.Entity("MyTranslator.Api.Data.ProtectedBlock", b =>
                {
                    b.HasOne("MyTranslator.Api.Data.TranslationTask", "Task")
                        .WithMany("ProtectedBlocks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("MyTranslator.Api.Data.TranslationSegment", b =>
                {
                    b.HasOne("MyTranslator.Api.Data.TranslationTask", "Task")
                        .WithMany("Segments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("MyTranslator.Api.Data.TranslationRun", b =>
                {
                    b.HasOne("MyTranslator.Api.Data.TranslationTask", "Task")
                        .WithMany("TranslationRuns")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("MyTranslator.Api.Data.TranslationRunFailure", b =>
                {
                    b.HasOne("MyTranslator.Api.Data.TranslationRun", "Run")
                        .WithMany("Failures")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("MyTranslator.Api.Data.TranslationRun", b =>
                {
                    b.Navigation("Failures");
                });

            modelBuilder.Entity("MyTranslator.Api.Data.TranslationTask", b =>
                {
                    b.Navigation("ProtectedBlocks");

                    b.Navigation("Segments");

                    b.Navigation("TranslationRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
